//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieBlogWebsite.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCONTACT
    {
        public int MESSAGEID { get; set; }
        public string NAMESURNAME { get; set; }
        public string MAIL { get; set; }
        public string PHONE { get; set; }
        public string SUBJ { get; set; }
        public string MESAGE { get; set; }
    }
}
